# Generated by Django 3.2.6 on 2022-06-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('unity_value', models.IntegerField(default=0, verbose_name='Unity')),
                ('quantity_product', models.IntegerField(default=0, verbose_name='Quantity')),
                ('status', models.CharField(default='', max_length=240, verbose_name='Status')),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
