# Generated by Django 3.2.6 on 2022-06-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220608_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=240, verbose_name='Product')),
                ('unity_value_request', models.IntegerField(default=0, verbose_name='UnityRequest')),
                ('quantity_product_request', models.IntegerField(default=0, verbose_name='QuantityRequest')),
                ('solicitation', models.DateTimeField(auto_now=True)),
                ('requester', models.CharField(max_length=240, verbose_name='Requester')),
                ('forwarding_agent', models.CharField(max_length=240, verbose_name='Requester')),
                ('address', models.CharField(max_length=240, verbose_name='Requester')),
                ('order_status', models.CharField(max_length=240, verbose_name='Requester')),
            ],
        ),
    ]
