# Generated by Django 3.2.6 on 2022-06-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_requestproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Status'),
        ),
    ]
